{
 "title": "backend",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (rate(api_response_code[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall RPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_incoming_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_incoming_requests{endpoint=~\"/api/v1/auth/register|/api/v1/auth/login|/api/v1/auth/logout|/api/v1/auth/me|/api/v1/auth/recovery|/api/v1/auth/settings|/api/v1/auth/verify/link|/api/v1/auth/verify/code/send|/api/v1/auth/verify/code/submit\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}